#+title: Readme for this test repo for DWM

This is a test repo for testing suckless's DWM with select patches from their website.

Follow commit history to know about patches added:

- in =commit:9b053a=, patch =swallow-20201211= added
- in =commit:7d9d9b=, patch =xrdb-6.4= added 
- patch =shift-tools-6.2= added in this commit
- patch =statuscmd-2026= added in this commit
- patch =moveresize-2022= added in this commit
- patch =pertag-2020= added in this commit
- patch =scratchpads-2020= added in this commit.  ~Rules[]~ array defined in this patch in the =config.def.h= file, clashes with that of =swallow-20201211= patch.  Additional modifications done.
- patch =gridall-6.5= combining the =gapless-grid= and the =winview= patches, added in this commit
- patch =keysequence-2025= added in this commit.  Additionally, added a template keysequence to =config.def.h= file.
- patch =spawn_window_cwd-6.6= added in this commit
- patch =cfacts-2020= added in this commit.  Keybindings described in this patch in the =config.def.h= file, clashes with those in =shift-tools-6.2=.  Additional, modifications done.
- patch =exitmenu-6.3= added in this commit
- patch =movestack-2021= added in this commit
- patch =fsignal-6.2= added in this commit
- patch =attachaside-6.6= added in this commit
- patch =focusonclick-6.6= added in this commit
- patch =bulkill-2023= added in this commit
- patch =clientresizehints-6.5= added in this commit
- patch =dragmfact-6.2= added in this commit
- patch =restoreafterrestart-2022= added in this commit
- patch =tiledmove-2023= added in this commit
- patch =focusbynum-2023= added in this commit.  Keybindings defined in this patch in the =config.def.h= file, clashes with those in =shift-tools-6.2=, =cfacts-2020= and =movestack-2021= patches.  Additional modifications done.
- patch =focusmaster-6.2= added in this commit
- patch =defaultmfact-6.5= added in this commit
- patch =cycleview-2024= added in this commit
- patch =zeroastag-2023= added in this commit
- patch =hide_vacant_tags-6.4= added in this commit
- patch =doublepressquit-6.3= added in this commit.  Requires modifying the ~quit~ function in =dwm.c= file, on top of the pre-existing modification by the =restoreafterrestart-2022= patch.
- patch =dmenumatchtop-6.2= added in this commit
- patch =alwayscenter-2020= added in this commit
- patch =colemak_keys-2020= added in this commit.  More modifications done to change keybindings of pre-existing patches to reflect ~colemak~ layout.  Additional changes to =dwm.1= manual file, reflecting new keybindings, as well as incorporating older keybindings from pre-existing patches.
