#+title: Readme for this test repo for DWM

This is a test repo for testing suckless's DWM with select patches from their website.

Follow commit history to know about patches added:

- in =commit:9b053a=, patch =swallow-20201211= added
- in =commit:7d9d9b=, patch =xrdb-6.4= added 
- patch =shift-tools-6.2= added in this commit
- patch =statuscmd-2026= added in this commit
- patch =moveresize-2022= added in this commit
- patch =pertag-2020= added in this commit
- patch =scratchpads-2020= added in this commit.  ~Rules[]~ array defined in this patch in the =config.def.h= file, clashes with that of =swallow-20201211= patch.  Additional modifications done.
- patch =gridall-6.5= combining the =gapless-grid= and the =winview= patches, added in this commit
- patch =keysequence-2025= added in this commit.  Additionally, added a template keysequence to =config.def.h= file.
- patch =spawn_window_cwd-6.6= added in this commit
- patch =cfacts-2020= added in this commit.  Keybindings described in this patch in the =config.def.h= file, clashes with those in =shift-tools-6.2=.  Additional, modifications done.
- patch =exitmenu-6.3= added in this commit
